version: "3.8"

services:
  backend:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:3000
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # HTTP UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  matching:
    build:
      context: ./matching-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672  
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
